In [12]:
import tensorflow as tf
import numpy as np
import pprint as pp



In [18]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

t = np.array([[0., 1.], [2., 3.]])

pp.pprint(t)
print(t.ndim)
print(t.shape)

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]
array([[0., 1.],
       [2., 3.]])
2
(2, 2)


In [22]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)

pp.pprint((matrix1 + matrix2))
# http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc Broadcasting참고

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4., 5.]], dtype=float32)>


In [30]:
print(tf.reduce_mean([1,2], axis=0))

x = [[1., 2.],
    [3., 4.]]

print(tf.reduce_mean(x))
print(tf.reduce_mean(x, axis=0))
print(tf.reduce_mean(x, axis=1))
print(tf.reduce_mean(x, axis=-1))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2.5, shape=(), dtype=float32)
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


In [33]:
print(tf.reduce_sum(x))
print(tf.reduce_sum(x, axis = 0))
print(tf.reduce_sum(x, axis = -1))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)


In [38]:
x = [[0, 1,2],
    [2, 1, 0]]
# axis 0 : 아래, axis 1 : ->
print(tf.argmax(x, axis=0))
print(tf.argmax(x, axis=1))
print(tf.argmax(x, axis=-1))

tf.Tensor([1 0 0], shape=(3,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)


In [49]:
x = np.array([[[0, 1, 2],
             [3, 4, 5]],
             
             [[6, 7, 8],
             [9, 10, 11]]])
print(x.shape)
print(tf.reshape(x, shape=[-1, 3]))

print(tf.reshape(x, shape=[-1, 1, 3]))

(2, 2, 3)
tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int64)
tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int64)
tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)


In [58]:
print(tf.squeeze([[0],[1],[2]]))
print(tf.expand_dims([0, 1, 2], 1))
one = tf.one_hot([[0], [1], [2], [0]], depth=3)
print(one)
print(tf.reshape(one, shape = [-1, 3]))

tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[[1. 0. 0.]]

 [[0. 1. 0.]]

 [[0. 0. 1.]]

 [[1. 0. 0.]]], shape=(4, 1, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]], shape=(4, 3), dtype=float32)


In [62]:
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


In [63]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

print(tf.stack([x, y, z]))
print(tf.stack([x, y, z], axis = 1))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [65]:
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.ones_like(x))
print(tf.zeros_like(x))

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [66]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6
